local kinds = {
    spider = "spider",
    spider_warrior = "spider",
    spider_spitter = "spider",
    spider_hider = "spider",
    spider_dropper = "spider",
    -- shadowwaxwell = "companion",
    pigman = "pig",
    pigguard = "pig",
    merm = "merm",
    hound = "hound",
    icehound = "hound",
    firehound = "hound",
    walrus = "hound",
    beefalo = "beefalo",
    tallbird = "bird",
    krampus = "demon",
    spat = "sheep",
    bat = "bat",
    monkey = "monkey",
    bee = "bee",
    killerbee = "bee",
    frog = "frog",
    knight = "chess",
    knight_nightmare = "chess",
    bishop = "chess",
    bishop_nightmare = "chess",
    rook = "chess",
    rook_nightmare = "chess",
    bunnyman = "rabbit",
    nightmarebeak = "shadow_creature",
    crawlingnightmare = "shadow_creature",
    terrorbeak = "shadow_creature",
    crawlinghorror = "shadow_creature",
    tentacle = "tentacle",
    koalefant = "koalefant",
    koalefant_summer = "koalefant",
    rocky = "rocky",
    worm = "worm",
    -- boss
    leif = "leif",
    leif_sparse = "leif",
    warg = "hound",
    spiderqueen = "spider",
    deerclops = "world_boss",
    moose = "world_boss",
    dragonfly = "world_boss",
    bearger = "world_boss",
    minotaur = "ancient_guard",
}

for k, v in pairs(kinds) do
    AddPrefabPostInit(k, function(inst)
        inst.creature_kind = v
    end)
end