local Info = Sample.Info
local TUNING = TUNING
local seg_time = 30
local total_day_time = seg_time * 16

-- weapon
-- TUNING.SPEAR_DAMAGE = 34 * .8
-- TUNING.HAMBAT_DAMAGE = 34 * 1.25
-- TUNING.RUINS_BAT_DAMAGE = 34 * 1.25
-- TUNING.OBSIDIAN_SPEAR_DAMAGE = 34 * 1.25
-- TUNING.CORK_BAT_DAMAGE = 34 * 1.25
-- TUNING.NIGHTSWORD_DAMAGE = 34 * 1.25
-- TUNING.SPIKE_DAMAGE = 34 * 1
-- TUNING.OBSIDIAN_SPEAR_DAMAGE = 34 * 1
-- TUNING.CUTLASS_DAMAGE = 34 * 1.25
-- TUNING.BATBAT_DAMAGE = 34 * 1
-- TUNING.HARPOON_DAMAGE = 100
-- TUNING.SPEAR_LAUNCHER_DAMAGE_MOD = 1.5
TUNING.GUNPOWDER_DAMAGE = 100
-- armor
-- TUNING.ARMORGRASS_ABSORPTION = .4
-- TUNING.ARMORWOOD_ABSORPTION = .5
-- TUNING.ARMOR_FOOTBALLHAT_ABSORPTION = .5
-- TUNING.ARMOR_RUINSHAT_ABSORPTION = .6
-- TUNING.ARMORRUINS_ABSORPTION = .6
-- TUNING.ARMOR_SANITY_ABSORPTION = .6
-- TUNING.ARMORMARBLE_ABSORPTION = .6
-- TUNING.ARMOR_OXHAT_ABSORPTION = .55
-- TUNING.ARMORDRAGONFLY_ABSORPTION = .5
-- TUNING.ARMOR_WATHGRITHRHAT_ABSORPTION = .6  -- 女武神头盔
-- TUNING.ARMOR_WATHGRITHRHAT = Info.Armor.ArmorAmount[2]
-- TUNING.ARMOR_SLURTLEHAT_ABSORPTION = .6
-- TUNING.ARMORVORTEX_ABSORPTION = .6
-- TUNING.ARMORMETAL_ABSORPTION = .55
-- TUNING.ARMOR_KNIGHT_ABSORPTION = .55
-- TUNING.ARMORSEASHELL_ABSORPTION = .5
-- TUNING.ARMORBRAMBLE_ABSORPTION = .6  -- 虫木的荆棘甲
-- TUNING.ARMORLIMESTONE_ABSORPTION = .4
-- TUNING.ARMORCACTUS_ABSORPTION = .5
-- TUNING.ARMOR_WEEVOLE_ABSORPTION = .4  -- 甲虫护甲
-- electric damage
TUNING.ELECTRIC_DAMAGE_MULT = 1
TUNING.ELECTRIC_WET_DAMAGE_MULT = 1
-- rocky
TUNING.ROCKY_ABSORB = .25
TUNING.ROCKY_REGEN_AMOUNT = 3
-- sw
TUNING.DO_SEA_DAMAGE_TO_BOAT = false