local cn_other_strs = {
	tp_reng = '扔',
	tp_tou = '冲',
	tp_hua = '滑',
	tp_za = '跳斩',
	tp_ci = '突刺',
	tp_cui_feng = '风',
	tp_wind_attack = '瞬移斩',
	tp_rotate = "旋斩",
	tp_bangalore = "火药桶",
	tp_load_ammo = '装填',
	tp_sea_sleep = '睡觉',
	tp_sea_dry = '晾干',
	tp_change = '改变',
	tp_diving = '潜水',
	tp_use = '使用',
	tp_zhuan = "劈砍",
	tp_inter = "使用",
	tp_craft = "制作",
	tp_madvalue_med = "诅咒加深了",
	tp_madvalue_hei = "诅咒就要来临了",
	-- tp_gift_pigking = '猪王的礼物',
	-- tp_gift_gingko = '银杏的礼物',
	-- tp_gift_alloy = '熔炉的礼物',
	tp_gift_pigking = '重击器',
	tp_gift_gingko = '打蛋器',
	tp_gift_alloy = '潜水镜',
	tp_gift_4 = "囚嘤笼",
	tp_gift_5 = "灌溉桶",
	tp_pig_fire = '炎拳',
	tp_pig_ice = '为了巫妖王',
	tp_pig_poison = '主宰',
	tp_pig_thunder = "为了雷霆崖",
	tp_pig_blood = "为了辛多雷的荣耀",
	tp_pig_shadow = "一代又一代的英雄\n选择了野影刀",
	tp_select_tile = "社区温暖礼包",
	tp_select_word = "百万福利\n点击就送\n点一下，玩一年\n装备不花一分钱\n\n\n\n选择你的礼物",
	tp_shop_word = "需要20级才能打开",
	tp_wendy_str =
		{
			"威尔逊",
			"这是沃格斯塔夫给你的礼物",
			"请你收下",
		},
	tp_wendy_str2 =
	{
		"恭喜你，威尔逊",
		"你已经成功升到四级以上",
		"可以开启一条新的支线",
		"满级后会有最后一条支线等着你",
	},
	tp_wendy_str3 =
	{
		"太棒了，威尔逊",
		"现在，你已经升到满级了",
		"快来开启最后一条支线吧",
	},
	tp_wendy_str4 =
	{
		"威尔逊你好",
		"近期版本进行了较大更新",
		"请查看《更新公告》",
	},
	tp_wendy_str5 =
	{
		"威尔逊你好",
		"沃格斯塔夫把森林之枪进行了强化",
		"现在可以同时装填4种树果",
		"不同的树果会有不同的效果",
		"松果会让森林之枪拥有更远的攻击距离",
		"橡果子弹会造成范围伤害",
		"丛林树果子弹击中敌人会回复你的生命值",
		"茶树果子弹击中敌人后会令敌人昏睡",
		"快去试试吧",
	},
	tp_wendy_str6 =
	{
		"太棒了，威尔逊",
	},
	tp_wendy_str7 = 
	{
		"威尔逊你好",
		"版本已更新",
		"请在《更新公告》里查看更新",
	},
	tp_curse = "诅咒已解除",
	tp_transport_plane_announce = "未检测到地面有捆绑物资",
}
local en_other_strs = {
	tp_reng = 'throw',
	tp_tou = 'cast' ,
	tp_hua = 'slide',
	tp_za = 'jump',
	tp_ci = 'lunge',
	tp_cui_feng = 'Wind',
	tp_wind_attack = 'Wind Attack',
	tp_rotate = "Rotate",
	tp_bangalore = "Bangalore",
	tp_load_ammo = 'load',
	tp_sea_sleep = 'Sleep',
	tp_sea_dry = 'Dry',
	tp_change = 'change',
	tp_diving = 'Diving',
	tp_use = 'Use',
	tp_zhuan = 'Rotate',
	tp_inter = "Interact",
	tp_craft = "Craft",
	tp_madvalue_med = "Curse is deepth",
	tp_madvalue_hei = "Cuse is Coming",
	-- tp_gift_pigking = "Gift of the Pig King",
	-- tp_gift_gingko = "Gift of Ginkgo",
	-- tp_gift_alloy = "Gift of Forge",
	tp_gift_pigking = "Gift of the Pig King",
	tp_gift_gingko = "Gift of Ginkgo",
	tp_gift_alloy = "Gift of Forge",
	tp_gift_4 = "Gift 4",
	tp_gift_5 = "Gift 5",
	tp_pig_fire = 'Fire Punch',
	tp_pig_ice = 'for the Lich King',
	tp_pig_poison = 'Juggernaut',
	tp_pig_thunder = "Thunder",
	tp_pig_blood = "Blood",
	tp_pig_shadow = "Shadow",
	tp_select_tile = "Maxwell's Gift",
	tp_select_word = "\nthe Pig King,\nGingko Tree\nOr\nWar Furnace\n\n\n",
	tp_shop_word = "need lv 20",
	tp_wendy_str = "This Wagstaff gift, blees wish",
	tp_wendy_str2 = "Good Luck",
	tp_wendy_str3 = "Good Luck",
	tp_wendy_str4 = "Hello Wilson",
	tp_wendy_str5 = "Hello Wilson",
	tp_wendy_str6 = "Good Job",
	tp_wendy_str7 = "Hello Wilson",
	tp_curse = "The curse is lifted",
}

local cn_strs = {
	-- tp_ash = {'威尔逊的粉末', '可以合成一些东西', nil},
	-- beefalo_sp = {'牛来', nil, nil},
	-- tp_perd = {'威尔逊的火鸡', '快去干活', nil},
	tp_gingko = {'银杏树苗', '银杏树的果实'},
	tp_war_tree_seed = {'战争树苗', '长大后可以用松果雇佣'},
	tp_defense_tree_seed = {'哨兵树苗', '长大后可以当个保安'},
	tp_life_tree_seed = {'生命树苗', '长大后可以召唤蔬菜'},
	-- tp_beefalo = {'骑骑', '它很温顺'},
	-- tp_baby_beefalo = {'威尔逊的小牛', '它现在还不能骑'},
	-- tp_gift_pigking = {'猪王的礼物', '打开看看'},
	-- tp_gift_gingko = {'银杏的礼物', '打开看看'},
	-- tp_gift_alloy = {'工坊的礼物', '打开看看'},
	bigfoot_sp = {'脚来', nil, nil},
	morph_sp = {'变身', nil, nil},
	callbeast_sp = {'九牛二猪', nil, nil},
	tp_pig_fire = {'黄耳·叶龙', '火焰果实的持有者', nil},
	tp_pig_ice = {'青鬃·萨恩', '冰霜果实的持有者', nil},
	tp_pig_poison = {'绿鼻·格林', '剧毒果实的持有者', nil},
	tp_pig_thunder = {'蓝背·布鲁', '雷霆果实的持有者'},
	tp_pig_blood = {'赤蹄·瑞德', '猩红果实的持有者'},
	tp_pig_shadow = {'紫牙·品克', '昏睡果实的持有者'},
	tp_spear_lance = {'投掷长矛', '可以投掷', '把石头磨尖'},
	tp_spear_ice = {'冰霜战矛', '攻击会冰冻敌人'},
	tp_spear_fire = {'火焰战矛', '攻击会引燃敌人'},
	tp_spear_thunder = {'雷电战矛', '射出电磁炮攻击多名敌人'},
	tp_spear_gungnir = {'突刺长矛', '使用它突刺', '把石头磨尖'},
	tp_spear_poison = {'剧毒战矛', '攻击敌人会使敌人中毒\n并降低敌人一半的移速'},
	tp_spear_shadow = {'暗影战矛', '攻击力等于理智百分比\n会秒杀影怪'},
	tp_spear_blood = {'鲜血战矛', '攻击会获得生命回复，\n怪物越大回复越高'},
	tp_spear_wrestle = {'竞技长矛', '横扫千军', '把石头磨尖'},
	tp_spear_lightning = {'闪电战矛', '攻击有几率引来闪电'},
	tp_spear_speed = {'速度战矛', '攻击敌人会增加自己的移速'},
	tp_spear_earth = {'大地战矛', '攻击时会释放冲击波'},
	tp_spear_shine = {'闪耀战矛', '持续发光并降低耐久\n攻击时会增加耐久'},
	tp_spear_gold = {'赏金猎人', '击杀怪物，大型生物\n或史诗生物会获得赏金'},
	tp_spear_combat = {'战斗热诚', '攻击会不断提升攻击力'},
	tp_spear_beefalo = {'牦牛杀手', '对皮弗娄牛造成额外伤害'},
	tp_spear_bag = {"亚空间", "带有容器的长矛"},
	tp_spear_diamond = {"鲁珀特之泪", "完全防御，损坏后\n会杀死主人"},
	tp_spear_trap = {"荆棘花园", "攻击敌人时有几率\n在敌人脚下生成陷阱"},
	tp_spear_tornado = {'飓风战矛', "攻击有几率召唤旋风"},
	tp_spear_conqueror = {"征服者", "五次攻击后，攻击敌人将会\n回复体力、回复理智、\n造成额外伤害"},
	tp_spear_shoot = {"脉冲战矛", "消耗荧光果射出光球"},
	tp_spear_mix = {'融合战矛', '集百家之长'},
	tp_spear_wind = {'森林之杖', '指挥风之精灵作战', '风之精灵为你助阵'},
	tp_strawhat = {'精灵草帽', '决定就是你了', '让火鸡成为工具火鸡'},
	tp_strawhat2 = {'精灵草帽', '决定就是你了'},
	tp_strawhat_saddle = {'精灵草帽鞍', '决定就是你了'},
	tp_strawhat_trap = {'精灵草帽陷阱', '决定就是你了'},
	tp_ballhat = {'战斗头盔', '受到伤害有几率提高战力', '拥抱战斗的荣耀'},
	tp_woodarmor = {'锯齿木甲', '手持的防具', '木质板砖'},
	tp_hambat = {'威尔逊的火腿', '攻击时有几率掉落小肉', '戳破天际'},
	tp_staff_trinity = {'三一魔杖', '可以切换状态'},
	tp_tent = {'大帐篷', '睡个好觉', '可以修的帐篷'},
	tp_rocket = {'人工降雨', '准备发射', '晴天降雨，雨天停雨'},
	tp_cane = {'滑行手杖', '我得换条好点的裤子', '我建议滑着走'},
	tp_ruinbat = {'远古短剑', '杀死四季boss会升级'},
	tp_ruinbat_bearger = {'熊獾短剑', '释放巨大冲击波'},
	tp_ruinbat_dragonfly = {'龙蝇短剑', '放置、引燃火药桶'},
	tp_ruinbat_deerclops = {'巨鹿短剑', '范围伤害，回血，冰冻'},
	tp_ruinbat_moose = {'鹿鹅短剑', '召唤旋风，瞬移跳砸'},
	tp_cutlass = {'旗鱼水剑', '对史诗级怪物造成额外伤害'},
	tp_sign_staff = {'路牌法杖', '召唤法阵消灭怪物'},
	tp_forest_gun = {'森林之枪', '可以用五种树果做子弹'},
	tp_unreal_sword = {'幻影剑', '消耗噩梦燃料可以召唤影子'},
	tp_unreal_wilson = {'威尔逊之影'},
	tp_oak_armor = {'橡木甲', '受到攻击召唤桦树精助阵'},
	tp_pig_book = {'猪王日记', '消耗猪皮或大肉召唤猪人'},
	tp_brave_amulet = {'勇气护符', '根据当前饥饿百分比获得\n攻击和防御加成，但饥饿\n消耗也会得到相应的增加'},
	tp_pig_lamp = {'猪拉丁神灯', '充能一天之后便可召唤灯神'},
	tp_pig_spirit = {'神灯之灵', '你管这玩意叫灯神'},
	tp_chest = {'潘多拉魔盒', '月圆时打开会出现影怪'},
	tp_gingko_leaf = {'银杏树叶', '叶落归根'},
	tp_gingko_tree = {'银杏树', '灰森林的成员'},
	tp_war_tree = {'战争古树', '给予松果可以雇佣的树精'},
	tp_defense_tree = {'哨兵树', '周围有怪物时会召唤橡果精攻击敌人'},
	tp_life_tree = {'生命之树', '每天会在周围生成蔬菜'},
	tp_gingko_spaling = {'银杏树苗', '十年树木，百年树人'},
	tp_war_tree_spaling = {'战争树苗', '孕育战争的精灵'},
	tp_life_tree_spaling = {'生命树苗', '世界之树的子嗣'},
	tp_defense_tree_spaling = {'哨兵树苗', '精灵守护着这个种子'},
	tp_chop_pig = {'伐木猪', '工具猪1号'},
	tp_hack_pig = {'砍工猪', '工具猪2号'},
	tp_farm_pig = {'农场猪', '工具猪3号'},
	tp_chop_pig_home = {'伐木猪屋', '把灯开一下'},
	tp_hack_pig_home = {'砍工猪屋', '把灯开一下'},
	tp_farm_pig_home = {'农场猪屋', '把灯开一下'},
	tp_bird_egg = {'威尔逊的蛋', '放心吧，我不会吃你的'},
	tp_bird_egg_cracked = {'威尔逊的鸟蛋', '小鸡快出来'},
	tp_small_bird = {'小锅鸟', '跟着我'},
	tp_teen_bird = {'大锅鸟', '它很方便'},
	-- tp_werepig_king = {'野猪王', '谁把他放出来了'},
	tp_werepig_king = {'月之领主', '谁把他放出来了'},
	tp_blood_lord = {"猩红领主", "它的利爪渴望鲜血"},
	tp_thunder_lord = {"雷霆领主", "它们人多势众"},
	tp_fire_lord = {"烈焰领主", "我简直不敢靠近他"},
	tp_ice_lord = {"冰霜领主", "看得我打冷颤"},
	tp_poison_lord = {"沼泽领主", "到处都是毒素"},
	tp_shadow_lord = {"幻影领主", "先解决一个"},
	tp_pigking_hat = {'猪王帽子', '必须要有一位猪人王'},
	tp_sign_rider = {'战争骑士', '小心她的路牌'},
	tp_sign_rider_2 = {'死亡骑士', '小心他的路牌'},
	tp_sign_rider_3 = {'瘟疫骑士', '小心他的路牌'},
	tp_sign_rider_4 = {'愤怒骑士', '小心他的路牌'},
	tp_smelter = {'战争熔炉', '用蓝宝石锻造合金', '冶炼合金'},
	tp_alloy = {'蓝色合金', '千锤百炼'},
	tp_gift = {'萌新礼包', '开局就送'},
	tp_cook_pot = {'威尔逊的烹饪锅', '它很方便'},
	tp_pack_crab = {'冰蟹背包', '保鲜效果明显'},
	tp_pack_dragonfly = {'火蜓背包', '烧掉一切'},
	tp_pack_rabbit = {'兔兔背包', '动若脱兔'},
	tp_pack_beefalo = {'牦牛背包', '与牛共舞'},
	tp_pack_catcoon = {'浣熊背包', '吸取周围的一些战矛'},
	tp_pack_hound = {'贪狼背包', '重置周围的狗牙陷阱'},
	tp_pack_bearger = {'小熊背包', '一个肉汤管两天'},
	tp_pack_deerclops = {'鹿角背包', '保险的极致是反鲜'},
	tp_pack_giant = {'巨人背包', '站在巨人脚下'},
	tp_grass_pigking = {'猪王草人', '另一位猪王', '我可以和它交易'},
	tp_raft = {'威尔逊的睡莲'},
	tp_octopus = {'章鱼王布偶', "小章鱼王"},
	tp_thumper = {'重击器-初号机', '看起来不是很稳'},
	tp_reporter = {'助手温蒂', '你总算来了'},
	-- tp_reporter2 = {'助手温蒂', '你总算来了'},
	-- tp_reporter3 = {'助手温蒂', '你总算来了'},
	tp_blue_warg = {"宝石座狼", "它的身体是由宝石镶嵌而成的"},
	tp_red_warg = {"宝石座狼", "它的身体是由宝石镶嵌而成的"},
	tp_epic = {'生命精华', '带在身上用来升级'},
	tp_bangalore = {'火药桶', 'Boom!!!'},
	tp_rider_spawner = {'天启骑士降临', nil, '警告，戴好牛帽！'},
	rider_sp = {'天启骑士降临', nil, '警告，戴好牛帽！'},
	tp_tree_elf = {"树精灵", "栖息在树上的精灵"},
	tp_desk = {"绘图台", "绘制你的卷轴"},
	tp_egg_tool = {"打蛋器", "给它个蛋", "打它蛋"},
	tp_intro = {"合成说明书", "我想我知道了", "查看合成图鉴"},
	tp_update = {"更新公告", "", "查看更新内容"},
	tp_diving_mask = {'潜水镜', '好想戴上它跳进池塘'},
	tp_leif = {'生命古树', '给它银杏树叶获得树苗'},
	tp_bench = {'武器锻造台', '将多把武器融合成一把'},
	tp_horn = {"遥远的呼唤", "号角声起，骑士降临"},
	tp_treasure_map = {"藏宝图", "寻找你的宝藏"},
	gold_primeape = {"黄金猿", "藏宝图就在它的身上"},
	tp_magic_book = {'魔法书目录', '存放你的卷轴'},
	tp_fix_powder = {"修理粉末", "维护你的装备"},
	tp_lab = {"制药台", "炼金研究所"},
	tp_farm_pile = {"灌溉土丘", "我应该种点什么", "小型农场"},
	tp_armor_lamellar = {"木制护甲", "保护你的躯壳"},
	tp_armor_health = {'复苏护甲', "残血时有几率回复生命"},
	tp_armor_firm = {'坚定护甲', '受到攻击不会硬直'},
	tp_armor_warm = {'烈火护甲', '受到攻击有几率点燃敌人'},
	tp_armor_cool = {'寒冰护甲', '受到攻击有几率冰冻敌人'},
	tp_armor_brier = {'反伤护甲', '对攻击你的敌人造成伤害'},
	tp_armor_thunder = {'雷霆护甲', '被闪电击中后会获得更多效果'},
	tp_armor_ancient = {"远古骑士", "受伤时有几率召唤骑士"},
	tp_armor_ancient2 = {"远古主教", "受伤时有几率召唤主教"},
	tp_armor_ancient3 = {"远古战车", "受伤时有几率召唤战车"},
	tp_hat_helm = {'战斗头盔II', '保护你的脑壳'},
	tp_hat_health = {"治愈头盔", "提高生命回复效果"},
	tp_hat_warm = {"御寒头盔", "延缓温度的降低"},
	tp_hat_cool = {"避暑头盔", "延缓温度的升高"},
	tp_hat_antitoxin = {"防毒头盔", "免疫中毒和毒气"},
	tp_hat_ancient = {"远古之冠", "对生命值较高的敌人\n造成百分比的伤害"},
	tp_potion_health_small = {"生命药剂", "持续回复生命值"},
	tp_potion_sanity_small = {"理智药剂", "持续回复理智值"},
	tp_potion_brave_small = {"镇静药剂", "降低诅咒值"},
	tp_potion_warth = {'愤怒药剂', "增加攻击力，持续掉理智"},
	tp_potion_crazy = {'疯狂药剂', "增加移速，持续掉理智"},
	tp_potion_shine = {'光芒药剂', "饮用后回发光一段时间"},
	tp_potion_dry = {'干燥药剂', '让你干燥的更快'},
	tp_potion_iron = {'钢铁药剂', "增加防御力，持续掉理智"},
	tp_potion_metal = {'金属药剂', '受伤无硬直，持续掉理智'},
	tp_potion_shadow = {'幻影药剂', '饮用后会隐身，持续掉理智'},
	tp_potion_killer = {'杀戮药剂', '大幅提升攻击力，降低血上限'},
	tp_potion_smell = {'气味药剂', '饮用后一段时间内\n不会被猎犬和牦牛所攻击'},
	tp_potion_cool = {'清凉药剂', '持续降温一段时间'},
	tp_potion_warm = {'温暖药剂', '持续升温一段时间'},
	tp_potion_detoxify = {'解毒药剂', '解除中毒状态'},
	tp_potion_horror = {'恐怖药剂', '生命值和理智值百分比互换'},
	tp_plantable_reeds = {'芦苇之茎', '种植出芦苇'},
	tp_plantable_flower_cave = {'荧光之茎', '种植出荧光果'},
	tp_plantable_grass_water = {'水草之茎', '种植出水草'},
	tp_plantable_mangrove = {'红树之茎', '种植出红树'},
	tp_fake_knight = {'伪骑士', '你不是这幅盔甲的主人'},
	tp_hornet = {'小黄蜂', "留个联系方式好吗"},
	tp_combat_lord = {'锯齿领主', "精通战斗的姐妹组合"},
	tp_combat_lord2 = {'锯齿领主', "精通战斗的姐妹组合"},
	tp_combat_lord3 = {'锯齿领主', "精通战斗的姐妹组合"},
	tp_soul_student = {"灵魂学徒", "灵魂大师的学徒"},
	tp_fool_spider = {"愚者蜘蛛", "蠢家伙的未来"},
	tp_warg_rider= {"座狼骑士", "黑色的怪物"},
	tp_combat_lord_sleep = {'沉睡的锯齿领主', "我最好别去招惹她"},
	tp_hornet_sleep = {'沉睡的小黄蜂', '也许我可以试试'},
	tp_fake_knight_sleep = {'沉睡的伪骑士', "他看上去很好对付"},
	tp_soul_student_sleep = {'沉睡的灵魂学徒', "我们应该做好准备"},
	tp_dragon_cage = {'囚嘤笼', '喂它能掉落宝物'},
	tp_dragonfly_ice_statue = {'龙蝇冰雕', nil, '可以驱散巨人的诅咒'},
	tp_bearger_ice_statue = {'熊獾冰雕', nil, '可以驱散巨人的诅咒'},
	tp_moose_ice_statue = {'鹿鸭冰雕', nil, '可以驱散巨人的诅咒'},
	tp_deerclops_ice_statue = {'巨鹿冰雕', nil, '可以驱散巨人的诅咒'},
	tp_shadow_statue = {"暗影雕像", "月圆时会召唤影怪", "梦魇的召唤者"},
	tp_pot_bird = {"蓝鸟", "可以变成锅"},
	tp_pot_bird_egg = {"蓝鸟的蛋", "吸引蓝鸟"},
	tp_red_dragon = {'红龙', '带着大号的背包'},
	tp_red_dragon_sack = {'红龙的背包', "吸引红龙"},
	tp_transport_plane = {"运输火箭", nil, "空降打包袋"},
	tp_bat_scythe = {"收获镰刀", "快速采集资源"},
	tp_moon_lake = {"月光湖"},
}
local en_strs = {
	tp_war_tree_seed = {'war tree spaling', 'Hurry and grow up'},
	tp_defense_tree_seed = {'defense tree spaling', 'Hurry and grow up'},
	tp_life_tree_seed = {'life tree spaling', 'Hurry and grow up'},
	tp_gingko = {'gingko spaling', 'Hurry and grow up'},
	bigfoot_sp = {'Big Foot', nil, nil},
	morph_sp = {'Morph', nil, nil},
	callbeast_sp = {'Herd', nil, nil},
	tp_pig_fire = {'Fire Pig', 'It is a fire pig', nil},
	tp_pig_ice = {'Ice Pig', 'It is a ice pig', nil},
	tp_pig_poison = {'Poison Pig', 'It is a poison pig', nil},
	tp_spear_lance = {"Wilson's spear", 'I love this'},
	tp_spear_ice = {'ice spear', 'the spear have gem power'},
	tp_spear_fire = {'fire spear', 'the spear have gem power'},
	tp_spear_thunder = {'thunder spear', 'the spear have gem power'},
	tp_spear_gungnir = {"Wilson's spear", 'I love this'},
	tp_spear_poison = {'poison spear', 'the spear have gem power'},
	tp_spear_shadow = {'shadow spear', 'the spear have gem power'},
	tp_spear_blood = {'blood spear', 'the spear have gem power'},
	tp_spear_wind = {'Fallen Leaves', 'the wind elf'},
	tp_strawhat = {'straw hat', 'this is speical'},
	tp_strawhat2 = {'straw hat', 'this is speical'},
	tp_strawhat_saddle = {'straw saddle', 'this is speical'},
	tp_strawhat_trap = {'straw trap', 'this is speical'},
	tp_ballhat = {'Combat Helmet', 'join the fight'},
	tp_woodarmor = {'Sawtooth Armor', 'right way'},
	tp_hambat = {"Wilson's ham", 'good ham'},
	tp_staff_trinity = {'Trinity Staff', 'one is full'},
	tp_tent = {'big tent', 'have a good sleep'},
	tp_rocket = {'mini rocket', 'shoot sky'},
	tp_cane = {'slide cane', 'I need a great pants'},
	tp_ruinbat = {"Gatekeepers' Dagger", 'Blow the enemy'},
	tp_ruinbat_bearger = {"Gatekeepers' Dagger", 'with soul of giant'},
	tp_ruinbat_dragonfly = {"Gatekeepers' Dagger", 'with soul of giant'},
	tp_ruinbat_deerclops = {"Gatekeepers' Dagger", 'with soul of giant'},
	tp_ruinbat_moose = {"Gatekeepers' Dagger", 'with soul of giant'},
	tp_cutlass = {'Water Cutlass', 'walking on water'},
	tp_sign_staff = {'Home Sign', 'sign of home'},
	tp_forest_gun = {'Forest Gun', "It has its name in the elf's song"},
	tp_unreal_sword = {'Unreal Sword', "It's Maxwell's?"},
	tp_unreal_wilson = {'shadow of Wilson'},
	tp_oak_armor = {'Oak Armor', 'the abode of the elves'},
	tp_pig_book = {'Pigking Journal', '... how to be king'},
	tp_brave_amulet = {'Brave Amulet', 'mountain of courage'},
	tp_pig_lamp = {"Pigladdin's Magic Lamp", 'Hello, Pigladdin'},
	tp_pig_spirit = {'Lamp Spirit', 'what?'},
	tp_chest = {"Pandora's Box", 'Cursed treasure chest'},
	tp_gingko_leaf = {'ginkgo biloba', 'Can I do it?'},
	tp_gingko_tree = {'gingko tree', 'Member of Grey Forest'},
	tp_war_tree = {'war tree', 'the Old Soldier'},
	tp_defense_tree = {'defense tree', 'the Old Guard'},
	tp_life_tree = {'life tree', "Children of the World Tree"},
	tp_war_tree_spaling = {'war tree spaling', 'Hurry and grow up'},
	tp_defense_tree_spaling = {'defense tree spaling', 'Hurry and grow up'},
	tp_life_tree_spaling = {'life tree spaling', 'Hurry and grow up'},
	tp_gingko_spaling = {'gingko spaling', 'Hurry and grow up'},
	tp_chop_pig = {'chopper', 'No.001'},
	tp_hack_pig = {'hacker', 'No.002'},
	tp_farm_pig = {'farmer', 'No.003'},
	tp_chop_pig_home = {'chopper house', 'turn off the lights'},
	tp_hack_pig_home = {'hacker house', 'turn off the lights'},
	tp_farm_pig_home = {'farmer house', 'turn off the lights'},
	tp_bird_egg = {"Wilson's bird egg", "Don't worry"},
	tp_bird_egg_cracked = {"Wilson's bird egg", "Don't worry"},
	tp_small_bird = {'small pot bird', 'follow me'},
	tp_teen_bird = {'big pot bird', 'looks good'},
	tp_werepig_king = {'Werepig King', 'Who let him out'},
	tp_pigking_hat = {'Pig King Hat', 'There must be a pig king'},
	tp_sign_rider = {'Knights of the Apocalypse', 'Be Careful'},
	tp_sign_rider_2 = {'Knights of the Apocalypse', 'Be Careful'},
	tp_sign_rider_3 = {'Knights of the Apocalypse', 'Be Careful'},
	tp_sign_rider_4 = {'Knights of the Apocalypse', 'Be Careful'},
	tp_smelter = {'War Furnace', 'forged alloy'},
	tp_alloy = {'blue alloy', 'dental laboratories'},
	tp_gift = {"Maxwell's Gift", 'open and see'},
	tp_cook_pot = {"Wilson's cooking pot", 'looks good'},
	tp_pack_crab = {'crab pack', 'It is like crab'},
	tp_pack_dragonfly = {'dragonfly pack', 'It is like dragonfly'},
	tp_pack_rabbit = {'rabbit pack', 'It is like rabbit'},
	tp_pack_beefalo = {'beefalo pack', 'It is like beefalo'},
	tp_pack_catcoon = {'catcoon pack', 'It is like catcoon'},
	tp_pack_hound = {'hound pack', 'It is like hound'},
	tp_pack_bearger = {'bear pack', "I'm hungery"},
	tp_grass_pigking = {'pig king statue', 'So humble'},
	tp_raft = {"Wilson's log raft"},
	tp_octopus = {"octopus doll", "small octopus"},
	tp_thumper = {"Wilson's thumper", "good machine"},
	tp_reporter = {'Wendy', 'hi, Wendy'},
	tp_reporter2 = {'Wendy', 'hi, Wendy'},
	tp_reporter3 = {'Wendy', 'hi, Wendy'},
	tp_blue_warg = {"Gem Warg", "A body made of gems"},
	tp_red_warg = {"Gem Warg", "A body made of gems"},
	tp_epic = {'Essence of life', 'eat it'},
	tp_bangalore = {'Bangalore', 'Boom!'},
	tp_rider_spawner = {"Apocalypse Coming"},
	tp_tree_elf = {"tree elf", "one of elves"},
}

local cn_scroll_strs = {
	tentacle 	= {"大地之触", "召唤触手", },
	bird 		= {"百鸟朝凰", "召唤鸟类", },
	lightning 	= {"诸神之怒", "召唤闪电", },
	sleep 		= {"梦游仙境", "催眠周围的生物", },
	grow 		= {"精灵之歌", "催熟周围的植物", },
	volcano 	= {"火山爆发", "召唤陨石", },
	wind 		= {"风之卷轴", "提供长时间加速", },
	pigman		= {"猪人卷轴", "召唤一个跟随你的猪人", },
	bunnyman	= {"兔人卷轴", "召唤一个跟随你的兔人", },
	shadow 		= {"暗影卷轴", "召唤一个威尔逊之影", },
	harvest 	= {"采收卷轴", "采收周围的作物", },
	pig_armor 	= {"守护卷轴", "为猪人提供护甲", },
	pig_armorex = {"庇佑卷轴", "增加猪人的防御", },
	pig_speed 	= {"神速卷轴", "增加猪人的移速", },
	pig_damage 	= {"狂野卷轴", "增加猪人的伤害", },
	pig_teleport= {"传送卷轴", "传送到草人旁边", },
	pig_heal	= {"恢复卷轴", "为猪人提供回复", },
	pig_leader	= {"征召卷轴", "收买周围的猪人", },
	pig_health 	= {"祝福卷轴", "提升猪人血上限", },
}
local en_scroll_strs = {
	tentacle 	= {"Page Tentacle", "", },
	bird 		= {"Page Bird", "", },
	lightning 	= {"Page Brimstone", "", },
	sleep 		= {"Page Sleep", "", },
	grow 		= {"Page Garden", "", },
	volcano 	= {"Page Meteor", "", },
	wind 		= {"Page Wind", "", },
	pig_armor 	= {"Page Armor", "", },
	pig_armorex = {"Page Defense", "", },
	pig_speed 	= {"Page Speed", "", },
	pig_damage 	= {"Page Damage", "", },
	pig_teleport= {"Page Teleport", "", },
	pig_heal	= {"Page Heal", "", },
	pig_leader	= {"Page Leader", "", },
	pig_health 	= {"Page Wish", "", },
}

for k, v in pairs(cn_scroll_strs) do
	cn_strs["scroll_"..k] = v
end
for k, v in pairs(en_scroll_strs) do
	en_strs["scroll_"..k] = v
end

GLOBAL.WARGON.STRING = {
	cn_other_strs = cn_other_strs,
	en_other_strs = en_other_strs,
	cn_strs = cn_strs,
	en_strs = en_strs,
}