local tuning = TUNING
-- fix: amrorwood, spear, hambat, footballhat
tuning.SPEAR_DAMAGE = 34 * .9
tuning.HAMBAT_DAMAGE = 34 * 1.5
tuning.ARMORWOOD_ABSORPTION = .7
tuning.ARMOR_FOOTBALLHAT_ABSORPTION = .7
tuning.DEERCLOPS_HEALTH = 3000
tuning.DRAGONFLY_HEALTH = 3000
tuning.MINOTAUR_HEALTH = 3000
tuning.TIGERSHARK_HEALTH = 3000
tuning.ANCIENT_HERALD_HEALTH = 3000