local sounds = {
    attack = "dontstarve/wilson/attack_weapon",
    -- laser = "",
    halberd = "dontstarve_DLC003/common/items/weapon/halberd",
    cutlass = "dontstarve_DLC002/common/swordfish_sword",
    get_item = "dontstarve/HUD/collect_resource",
    meat_rack = "dontstarve/common/craftable/meat_rack",
    chest_open = "dontstarve/wilson/chest_open",
    chest_close = "dontstarve/wilson/chest_close",
    turn_on = "dontstarve_DLC001/common/firesupressor_on",
    turn_off = "dontstarve_DLC001/common/firesupressor_off",
    spawn_shadow = "dontstarve/common/ghost_spawn",
    drop_water = "dontstarve_DLC002/common/item_float",
    mine = "dontstarve/wilson/use_pick_rock",
    staff = "dontstarve/wilson/use_gemstaff",
    magic_scroll = "dontstarve/common/deathpoof",
    -- magic_scroll = "dontstarve/common/staffteleport",
    cyclone_slash = "dontstarve_DLC003/common/items/weapon/halberd",
    attack_leap = "dontstarve_DLC001/creatures/bearger/dustpoof",
    lightning = "dontstarve/rain/thunder_close",
    thunder = "dontstarve/rain/thunder_close",
    bishop_charge = "dontstarve/creatures/bishop/shotexplo",
}

return sounds