return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 10,
  height = 10,
  tilewidth = 32,
  tileheight = 32,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "../dont_starve/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "../dont_starve/tiles.png",
      imagewidth = 512,
      imageheight = 384,
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0,
        7, 0, 9, 0, 7, 0,
        0, 0, 0, 0, 0, 0,
        9, 0, 9, 0, 9, 0,
        0, 0, 0, 0, 0, 0,
        7, 0, 9, 0, 7, 0
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "tp_point_postman",
          shape = "rectangle",
          x = 160,
          y = 160,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },

        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 8,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 8,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 24,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 24,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 40,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 40,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 56,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 56,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 72,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 72,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 88,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 88,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 104,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 104,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 120,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 120,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 312,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 312,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 296,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 296,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 280,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 280,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 264,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 264,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 248,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 248,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 232,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 232,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 216,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 216,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 200,
          y = 128,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 200,
          y = 192,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 8,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 24,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 40,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 56,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 72,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 88,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 104,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 120,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 312,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 296,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 280,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 264,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 248,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 232,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 216,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 128,
          y = 200,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 8,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 24,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 40,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 56,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 72,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 88,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 104,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 120,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 312,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 296,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 280,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 264,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 248,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 232,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 216,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tp_wall_wood",
          shape = "rectangle",
          x = 192,
          y = 200,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
      }
    }
  }
}
