local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS
if GetModConfigData("languages") == 1 then
	STRINGS.CHARACTER_TITLES.bulingbuling = "不灵小姐"
	STRINGS.CHARACTER_NAMES.bulingbuling = "BulingBuling"
	STRINGS.CHARACTER_DESCRIPTIONS.bulingbuling = "*因为失眠和胃病而苦恼\n*力气极小压根没法打 \n*从出生开始就被某个存在注视着"
	STRINGS.CHARACTER_QUOTES.bulingbuling = "\"科技不是第一战斗力\""
	STRINGS.CHARACTERS.BULINGBULING = require "speech_bulingbuling"
	--物品
	STRINGS.NAMES.BULING_GLOMLING = "机械格罗咪飞机器"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GLOMLING= "因为材料问题它没有搭载太多移动以外的必要组件"
	STRINGS.NAMES.BULING_FLOUR = "面粉"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FLOUR= "萃取器精加工的产物"
	STRINGS.NAMES.BULING_SYSTEM = "飞船终端"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SYSTEM= "它会告诉我该怎么做的"
	STRINGS.NAMES.BULING_PLANT_ZHONGZIDING = "塞德锭植株"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_ZHONGZIDING= "它会吸收地下的矿物质来制造塞德锭"
	STRINGS.NAMES.BULING_CHEST = "合金箱"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHEST= "结实又安全的箱子"
	STRINGS.NAMES.BULING_BANSHOU = "不灵扳手"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BANSHOU= "用来搬运机器"
	STRINGS.NAMES.BULING_MANUAL_ITEM = "合成台"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANUAL_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_MANUAL = "合成台"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANUAL= "为啥不是4个木头合成"
	STRINGS.NAMES.BULING_GLASS = "塞德玻璃"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GLASS= "把塞德锭萃取的话\n就能得到这种便宜玻璃\n这可真是神奇"
	STRINGS.NAMES.BULING_SEED_ZHONGZIDING = "塞德锭种子"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_ZHONGZIDING= "在它长成后会源源不断的生产塞德锭"
	STRINGS.NAMES.BULING_MANUAL = "不灵工作台"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANUAL= "它提供了3x3的合成空间供我使用"
	STRINGS.NAMES.BULING_ZHONGZIDING = "塞德锭"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGZIDING= "因为是可以种出来的，所以很环保\n我很青睐这种金属"
	STRINGS.NAMES.BULING_RONGLU_ITEM = "萃取机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RONGLU_ITEM= "放在地上用吧"
	STRINGS.NAMES.BULING_RONGLU = "萃取机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RONGLU= "用电力来萃取物质\n每次萃取需要消耗10Bp电力"
	STRINGS.NAMES.BULING_RADAR = "不灵雷达"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RADAR= "消耗庞大的电力进行一次极大范围的侦查\n需要800Bp的电力才能工作"
	STRINGS.NAMES.BULING_DIANLIFU = "电动斧"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANLIFU= "这种电力工具效率还不算坏"
	STRINGS.NAMES.BULING_JIANDAO = "合金剪"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANDAO= "这种工具耐久还不算坏"
	STRINGS.NAMES.BULING_DIANDONGGAO = "电动镐"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANDONGGAO= "这种电力工具效率还不算坏"
	STRINGS.NAMES.BULING_CROPBOX = "电动收割机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CROPBOX= "用于收割周围的植物\n需要50Bp的电力才能启动一次"
	STRINGS.NAMES.BULING_DIANDENG = "电灯"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANDENG= "我说，要有光\n耗电1Bp/s"
	STRINGS.NAMES.BULING_SHENGCUN = "生存发电机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHENGCUN= "燃烧寻常可见的燃料来发电，发电效率5Bp/5s\n补充一次燃料能用很久"
	STRINGS.NAMES.BULING_PAOTAI = "简易炮塔"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PAOTAI= "只有这些材料和工具我只能做到这种地步了\n没有电力时它将停止工作"
	STRINGS.NAMES.BULING_SOLARENERGY = "太阳能电池板MK1"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SOLARENERGY= "理所当然的发电机\n发电效率会随着天气变化而变化\n最佳环境时产电2Bp/s"
	STRINGS.NAMES.BULING_HUOSAI = "活塞引擎"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HUOSAI= "人力发电机\n发电效率全看人力\n最佳情况产电2Bp/s"
	STRINGS.NAMES.BULING_ZHONGJIQI = "电力中继器"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGJIQI= "用来储存并将电力供给其他机器"
	STRINGS.NAMES.BULING_SEEDBOX = "作物管家"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEEDBOX= "让作物冬天生长夏天不枯\n稍微增加作物生长速度\n耗电1Bp/s"
	STRINGS.NAMES.BULING_WEAPONCHEST = "机械加工炉"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WEAPONCHEST= "科技不是第一战斗力\n每次工作耗电50Bp"
	STRINGS.NAMES.BULING_CHONGDIANQI = "充电器"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHONGDIANQI= "用来给我的电力工具充电"
	STRINGS.NAMES.BULING_PLANTTABLE = "植物改良桌"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANTTABLE= "用来进行对植物的改良，因为没有使用电力，所以改造的程度有限"
	STRINGS.NAMES.BULING_DIANDENG_ITEM = "电灯"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANDENG_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_SHENGCUN_ITEM = "生存发电机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHENGCUN_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_HUOSAI_ITEM = "人力发电机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HUOSAI_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_SOLARENERGY_ITEM = "太阳能发电机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SOLARENERGY_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_ZHONGJIQI_ITEM = "电力中继器"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGJIQI_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_SEEDBOX_ITEM = "作物管家"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEEDBOX_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_PAOTAI_ITEM = "简易炮台"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PAOTAI_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_RADAR_ITEMFN = "不灵雷达"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RADAR_ITEMFN= "安置在地上使用"
	STRINGS.NAMES.BULING_CROPBOX_ITEM = "电动收割机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CROPBOX_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_WEAPONCHEST_ITEM = "机械加工炉"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WEAPONCHEST_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_CHONGDIANQI_ITEM = "充电器"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHONGDIANQI_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_PLANTTABLE_ITEM = "植物改良桌"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANTTABLE_ITEM= "安置在地上使用"
	STRINGS.NAMES.BULING_WAKUANG = "简易挖矿机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WAKUANG= "可以从地下挖矿"
	STRINGS.NAMES.BULING_WAKUANG_ITEM = "简易挖矿机"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WAKUANG_ITEM= "安置在地上使用"
	
	--种子&植株
	STRINGS.NAMES.BULING_PLANT_ROCK = "岩石植株"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_ROCK= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_PLANT_MARBLE = "大理石植株"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_MARBLE= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_PLANT_NITRE = "硝石植株"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_NITRE= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_PLANT_GOLD = "黄金植株"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_GOLD= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_PLANT_OBSIDIAN = "十胜石植株"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_OBSIDIAN= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_PLANT_FLINT = "燧石植株"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_FLINT= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_PLANT_WHEAT = "小麦"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_WHEAT= "非常好的粮食来源\n不过闪耀世界的麦子。。不长这样啊"
	STRINGS.NAMES.BULING_SEED_ROCK = "岩石种子"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_ROCK= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_SEED_MARBLE = "大理石种子"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_MARBLE= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_SEED_NITRE = "硝石种子"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_NITRE= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_SEED_GOLD = "黄金种子"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_GOLD= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_SEED_OBSIDIAN = "十胜石种子"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_OBSIDIAN= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_SEED_FLINT = "燧石种子"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_FLINT= "可以吸收土地中的矿物质"
	STRINGS.NAMES.BULING_SEED_WHEAT = "麦穗"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_WHEAT= "非常好的粮食来源"
	STRINGS.NAMES.BULING_MANURE = "钾硝肥"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANURE= "不错的廉价肥料"
	STRINGS.NAMES.BULING_MANURE_8 = "钾硝肥"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANURE_8= "不错的廉价肥料"
	--料理
	STRINGS.NAMES.BULING_COOKTABLE = "料理台"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOKTABLE= "用来制作料理\n可以做到完全除菌\n但是好像没什么用"
	STRINGS.NAMES.BULING_COOK_KAO = "烤制料理模块"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_KAO= "用来制作烤制料理\n开胃：临时增加饱食上限\n提神：临时增加精神上限\n健康：临时增加生命上限"
	STRINGS.NAMES.BULING_COOK_GUO = "锅料理模块"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_GUO= "用来制作锅料理\n养生：持续恢复生命\n美味：持续恢复精神\n饱腹:持续恢复饱食度"
	STRINGS.NAMES.BULING_COOK_ZHENG = "蒸煮料理模块"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_ZHENG= "用来制作蒸煮料理\n蒸煮料理会有各种特有buff"
	STRINGS.NAMES.BULING_BREAD = "面包"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BREAD= "烤制料理，食材\n非常普通的面包\n味道不是太好"
	STRINGS.NAMES.BULING_XIFAN = "稀饭"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_XIFAN= "锅料理，食材\n所谓的面稀饭\n填不饱肚子"
	STRINGS.NAMES.BULING_HONGGUZHOU = "红菇粥"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HONGGUZHOU= "锅料理\n稀饭里加了些蘑菇\n毒素解除：可以解毒"
	STRINGS.NAMES.BULING_LANGUZHOU = "蓝菇粥"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LANGUZHOU= "锅料理\n稀饭里加了些蘑菇\n养生:持续60秒"
	STRINGS.NAMES.BULING_LVGUZHOU = "绿菇粥"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LVGUZHOU= "锅料理\n味道不错\n美味：持续90秒"
	STRINGS.NAMES.BULING_SANGUBAO = "蘑菇天国"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SANGUBAO= "蒸煮料理\n蘑王弗兰克：持续120秒\n蘑王弗兰克：三维均临时提升\n不与烤制料理buff冲突"
	STRINGS.NAMES.BULING_AOLIAO = "可可饼"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_AOLIAO= "烤制料理\n释咖啡因\n像喝了咖啡一般"
	STRINGS.NAMES.BULING_LUOBUBAO = "萝卜煲"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LUOBUBAO= "蒸煮料理\n胡萝卜素：持续60秒\n胡萝卜素：夜视"
	STRINGS.NAMES.BULING_JIANGGUOMUSI = "浆果慕斯"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANGGUOMUSI= "徒手料理\n醇香浓厚\n美味:持续30秒"
	STRINGS.NAMES.BULING_BAOJIANGDANGAO = "爆浆蛋糕"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BAOJIANGDANGAO= "烤制料理\n甜美浆汁\n开胃:持续250秒"
	STRINGS.NAMES.BULING_BINGKAXIANBING = "宾卡馅饼"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BINGKAXIANBING= "烤制料理\n香酥可口\n提神:持续200秒"
	STRINGS.NAMES.BULING_MAPODOUFU = "麻婆豆腐"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MAPODOUFU= "锅料理\n为啥豆虫能做成豆腐呢\n炽热:持续60秒\n炽热：攻击时造成额外伤害"
	STRINGS.NAMES.BULING_KAOLENGMIAN = "烤冷面"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_KAOLENGMIAN= "烤制料理\n再来点辣酱\n开胃：持续30秒"
	STRINGS.NAMES.BULING_SANMINGZHI = "仙人掌三明治"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SANMINGZHI= "徒手料理\n超提神:持续10秒\n超提神：持续恢复大量精神"
	STRINGS.NAMES.BULING_JIANBINGGUOZI = "煎饼果子"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANBINGGUOZI= "烤制料理\n只能用叶肉做火腿了\n健康:持续180秒"
	STRINGS.NAMES.BULING_QIANCENGBING = "千层饼"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_QIANCENGBING= "蒸煮料理\n超饱腹:持续10秒\n超饱腹:持续恢复大量饱食"
	STRINGS.NAMES.BULING_XIANGCAOBUDING = "香草布丁"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_XIANGCAOBUDING= "蒸煮料理\n超美味:持续10秒\n超美味：持续恢复大量生命"
	STRINGS.NAMES.BULING_KAODIGUA = "烤地瓜"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_KAODIGUA= "烤制料理\n冬天穷人之友\n总之果腹没问题"
	--配方
	STRINGS.BUINGKEJI = "不灵科技"
	STRINGS.RECIPE_DESC.BULING_WEAPONCHEST_ITEM="加工机械零件"
	STRINGS.RECIPE_DESC.BULING_MANUAL="开发新点子的工作站"
	STRINGS.RECIPE_DESC.BULING_FADIANJI_SHENGCUN="更好的发电机"
	STRINGS.RECIPE_DESC.BULING_FADIANJI_HUOLI="进入电气时代"
	STRINGS.RECIPE_DESC.BULING_ZHONGJIQI="无线电池"
	STRINGS.RECIPE_DESC.BULING_WAKUANG_ITEM="更多的矿物"
	STRINGS.RECIPE_DESC.BULING_LINGJIAN="加工材料的车床"
	STRINGS.RECIPE_DESC.BULING_KUANGJIA="做机器的必备品"
	STRINGS.RECIPE_DESC.BULING_PAOTAI="基础守卫"
	--3x3配方
	STRINGS.BULING_ZHONGZIDING_SHUOMING = "很环保的金属\n用量会很大\n可以批量种植\n我大学毕业时研究的"
	STRINGS.BULING_SEED_ZHONGZIDING_SHUOMING = "1天就能成熟\n可反复收获\n应该大量种植"
	STRINGS.BULING_RONGLU_SHUOMING = "用于萃取材料\n每次萃取需要10Bp电力\n可储存200Bp电力"
	STRINGS.BULING_ZHONGJIQI_SHUOMING = "最重要的机器之一\n用于储存发电机输出的电力\n并将储存的电力供给其他机器\n自身也常用于机器合成"
	STRINGS.BULING_SHENGCUN_SHUOMING = "燃烧寻常可见的燃料来发电\n发电效率5Bp/5s\n补充一次燃料能用很久"
	STRINGS.BULING_PAOTAI_SHUOMING = "攻击力15\n生命50\n脆弱的炮塔\n每次耗电5Bp"
	STRINGS.BULING_RADAR_SHUOMING = "需要800Bp的电力才能工作\n探测一次全世界\n一段时间内玩家的地图全开\n退出游戏后重新变黑"
	STRINGS.BULING_CROPBOX_SHUOMING = "可以快速采集周围的作物\n需要50Bp的电力采集一次"
	STRINGS.BULING_DIANDENG_SHUOMING = "可以发出普通的光\n耗电5Bp/5s"
	STRINGS.BULING_WEAPONCHEST_SHUOMING = "生产实用装备\n每次工作耗电50Bp"
	STRINGS.BULING_SEEDBOX_SHUOMING = "可以照顾作物\n让作物冬天能够继续生长\n夏天不会枯萎"
	STRINGS.BULING_SOLARENERGY_SHUOMING = "利用阳光发电\n最大产电10Bp/5s"
	STRINGS.BULING_TOOL_SHUOMING = "一个很优秀的工具\n而且可以充电"
	STRINGS.GEARS_SHUOMING = "这种零件永远不会过时"
	STRINGS.BULING_CHONGDIANQI_SHUOMING = "用来给电力工具充电"
	STRINGS.BULING_BANSHOU_SHUOMING = "轻松搬运机器"
	STRINGS.BULING_PLANTTABLE_SHUOMING = "改良植物种子"
	STRINGS.BULING_CHEST_SHUOMING = "大箱子"
	STRINGS.BULING_SEED_SHUOMING = "通过基因改造\n来更好的获取资源"
	STRINGS.ROCK_SHUOMING = "这石头一点不圆润\n盘它！"
	STRINGS.SEEDS_SHUOMING = "让种子重新获得随机性"
	
	--杂项
	STRINGS.BULINGYANJIU = "研究"
	STRINGS.YUNSHI = "已捕捉到目标陨石"
	STRINGS.BULINGYANJIUSHIBAI = "我要在吃饱而且精神充足的情况下才能研究"
	STRINGS.CAILIAOBUZU = "材料不足"
	STRINGS.POWER = "电力"
	STRINGS.FUEL = "燃料"
	STRINGS.PROGRESS = "生产进度"
	STRINGS.BULINGITEM = "目标物品"
	STRINGS.BULINGTIME = "剩余时间"
	STRINGS.BULING_BWNG = "电力不足"
	STRINGS.BULING_STSTEM = "打开终端"
	STRINGS.BULING_LEIDA = "我从雷达上下载好临时的地图资料了"
	local STRINGS = GLOBAL.STRINGS
STRINGS.UI.WORLDGEN.BLTITLE = "前往外星球"
STRINGS.UI.WORLDGEN.BL_VERBS = {
    "产生",
    "畜牧",
    "浸湿",
    "迭代",
    "暗示",
    "网状化",
    "促进",
    "插入",
    "分配",
    "允许",
    "创造",
    "增殖",
    "灌溉",
    "测量",
}
STRINGS.UI.WORLDGEN.BL_NOUNS = {
    "肉胶",
    "痛苦",
    "月怪",
    "厄尔吉斯水晶",
    "怪物",
    "强烈的绝望感",
    "成桶成桶地战利品",
    "模组功能",
    "班花的胖次",
	"01的节操",
    "糖煎竹子",
    "宵征大佬",
    "吃撑的贝尔",
    "咸鱼干",
    "易汁黛苗",
    "nil",     
}
STRINGS.TASK = [[
	emmmmmmmmmmmm
]]
STRINGS.TASK1 = [[
本教程灵感来源自以下内容：
《我晚上看》《吃完饭再来》
《能用就行了》《咕咕咕咕咕咕咕咕咕咕》
《更新是不可能更新的,这辈子都不可能更新的》
《睡醒了看》《我怎么又睡着了》《明天再说》]]
STRINGS.TASK2 = [[
现在是x年x月x日，终端第5/5次尝试连接飞船数据库
---------------------------------------
连接失败，搜索不到飞船数据库，请在信号良好的地带重试
终端第5/5次尝试连接闪耀世界数据库
---------------------------------------
连接失败，搜索不到闪耀世界数据库，请在信号良好的地带重试
确定闪耀世界中心服务器信号丢失
再次确认，闪耀世界中心服务器信号丢失
终端认为你进入了未开化领域
终端认为完全没有野外生存经验的你会很快死掉
终端承认确实有什么在影响着你
K404航班穿梭机的失事率仅为0.003%
因为虫洞效应而离开闪耀世界范围的
理论机率仅为0.0002%
]]
STRINGS.TASK3 = [[
终端查阅了你的大学论文报告
终端认为你的一些作品能派的上用场
为了获取闪耀世界的救援你需要建立基站
以此和闪耀世界进行联系
为了实现这个目的你需要电力设备
终端找到了你毕业后设计的通讯机蓝图
尽管现在已经被新产品淘汰但是还是能用的
但是你至少得先得到矿产资源
]]
STRINGS.TASK4 = [[
好吧，对的，你以前有过类似的发明
终端查阅了你曾经写过的所有论文
你有设想过一种环保金属，塞德锭SeedSpindle
而且为了通过你的这篇论文。。
你有设计过一套相关的完整产业
希望你没有因为长期混在实验室完全忘掉手工操作
虽然终端也认为那些机械手臂非常好用
总之，终端认为你应该先搞出塞德锭
根据你的论文，塞德锭的核心是少量金属和种子胚胎
]]
STRINGS.TASK5 = [[
任务：通用金属
条件：获得1个塞德锭
说明：连塞德锭都没有你甚至都活不下去！
制作塞德锭的流程：
打开不灵工作台
按照图鉴摆材料后按下按钮
任务奖励？别傻了
{请将目标物品带在身上让终端检查}
]]
STRINGS.TASK6 = [[
看来你已经走出材料学的第一步了
但是别放松，这才刚刚开始
工业是靠材料堆出来的
仅仅几个塞德锭压根不够塞牙缝
别担心，塞德锭你可是宣城通用性最强的
你有设计过它的种植功能，能够大量生产的
但是在此之前，为了你那可怜的小胃着想
终端建议你最好解决肚子的问题
那么你应该制作出植物改良桌
这东西可以让你制作出诸如小麦之类的现代作物
地里有粮心里不慌，你以前最喜欢这么说了
]]
STRINGS.TASK7 = [[
任务：现代农业
条件：获得1个植物改良桌
说明：连粮食都没有你甚至都活不下去！
制作植物改良桌的流程：
打开不灵工作台
按照图鉴摆材料后按下按钮
{请将目标物品带在身上让终端检查}
]]
STRINGS.TASK8 = [[
终端认为你暂时可能饿不死了
大规模种地吧，为何记录的是你自己设计的麦子
终端表示不能理解
你忘了你为了对付大学毕业时设计的这东西有缺点了吗
它无法被移植，一旦被挖掉会变成最原始的种子
你之后设计的杂交植物都有这类缺点
都是因为你太懒，不想改良基因设计图
终端认为你早晚会因为懒癌遭报应的
这次飞船出事导致你开始荒野求生。。。
终端记得这个飞船用的燃油是你改良的。。。
终端认为这就是报应
不过如果你缺少原始种子的话
可以试图挖掉成熟植株来获得种子
]]
STRINGS.TASK9 = [[
你需要将食物进行加工才能食用
为此你需要电力来供应机器加工食物
终端认为你暂时没有足够的材料制作火力发电机
终端找到了你设计的人力发电机蓝图
终端无法理解设计人力发电机的理由
闪耀社会有戴森球供能，无需简陋的发电机
但是这个蓝图至少能救你一命

]]
STRINGS.TASK10 = [[
咕咕咕咕咕咕咕咕咕咕
]]
STRINGS.TASK11 = [[

]]
STRINGS.TASK12 = [[
如果你能看到这段信息

]]
STRINGS.TASK13 = [[

]]
STRINGS.TASK14 = [[
看来你制作出塞德锭种子了
这很好，空闲之余大量种植吧
工业化是用材料堆出来的
当你拥有了一定量的塞德锭后
你就可以开始试图制作机器了
首先是最重要的发电机
]]
STRINGS.TASK15 = [[
任务：电力曙光
条件：获得1个生存发电机
说明：能源的进步就是烧水方式的进步
制作生存发电机的流程：
打开不灵工作台
按照图鉴摆材料后按下按钮
{请将目标物品带在身上让终端检查}
]]
STRINGS.TASK16 = [[
音频日记备份2号开始播放
我必然会死，这点我十分确定
不牵扯到其他人类时我对自己的计算从不会出问题
但是我不会干脆的就这么死掉]]
STRINGS.TASK17 = [[我不会赌博
不会赌我死后人类能发展到能去对抗它们
听到这些的话，克隆人9527号
你继承了我的知识，虽然你在边缘地带
但是你有能力回来，回来拯救他们]]
STRINGS.TASK18 = [[现在你第一个任务
开始收集当地的矿物进行发展
这个地区远离闪耀世界，但是没有开化
我在该星球的轨道投放了不少卫星]]
STRINGS.TASK19 = [[你可以安心使用
不过生存下去更为重要
我的基因被不可名状的存在污染了]]
STRINGS.TASK20 = [[身为我的克隆人
你身上同样携带着我所拥有的病，咳咳
现在开始行动吧]]
STRINGS.TASK21 = [[]]
STRINGS.TASK22 = [[]]
STRINGS.TASK23 = [[]]
STRINGS.TASK24 = [[]]
STRINGS.TASK25 = [[]]
STRINGS.TASK26 = [[]]
STRINGS.TASK27 = [[]]
end